# data from SPS30 airborne particle sensor

uint64 timestamp			# time since system start (microseconds)

float32 mass_concentration_pm1_0
float32 mass_concentration_pm2_5
float32 mass_concentration_pm4_0
float32 mass_concentration_pm10_0

float32 number_concentration_pm0_5
float32 number_concentration_pm1_0
float32 number_concentration_pm2_5
float32 number_concentration_pm4_0
float32 number_concentration_pm10_0

float32 typical_particle_size

float32 relative_humidity
float32 temperature

float32 voc_index
float32 nox_index
